### ISSUE TITLE
error[E0554]: `#![feature]` may not be used on the stable release channel

### ISSUE THREAD

**Issue by mxmilkiib** [Windfisch/loopfisch#34]
Trying a `cargo build` but getting this atm;
```
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> src/main.rs:16:1
   |
16 | #![feature(proc_macro_hygiene)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by Windfisch** [comment]
Hi! This is true, you need to use the unstable toolchain.
You can add a per-directory override using `rustup override set nightly`.
You might need to update rust, for more information, you can refer to https://rocket.rs/v0.4/guide/getting-started/

(Please do not expect much yet; while the technical challenges are mainly solved, this project is not in an usable state yet.But feel free to experiment :))
